import type { HomeContent } from './home.types';

export const homeData: HomeContent = {
    engineerName: 'Sahinur Gain',
    title: 'Full Stack Software Engineer',
    location: 'Open to Remote & Relocation',
    avatar: '/hero.png',
    headlinePrefix: 'Full Stack Developer With',
    headlineGradient: '2.5+ Years of Experience',
    headlineSuffix: 'Building Scalable Web Systems.',
    subtitle:
        'Engineering high-impact web architectures, scalable microservices, and slick, performant client applications with production focus.',
    resumeUrl: '/Sahinur_Ali_Gain_Resume.pdf',
    resumeFileName: 'Sahinur_Ali_Gain_Resume.pdf',
    exploreBtnText: 'Explore Projects',
    contactBtnText: 'WhatsApp',
    resumeBtnText: 'Resume',
    whatsappNumber: '+91 98765 43210',
    whatsappMessage: 'Hi! I saw your portfolio and would like to connect.',
    stats: [
        { label: 'Experience', value: '2.5+ Yrs' },
        { label: 'Completed Projects', value: '15+' },
        { label: 'Client Rating', value: '100%' },
        { label: 'Availability', value: 'Immediate' },
    ],
    terminal: {
        name: 'Sahinur Gain',
        company: 'Techsunset (EMP: TS0542)',
        tenure: '08 April 2024 – Present',
        overallExp: '2.5+ Years',
        skills: [
            'Gen AI',
            'Javascript',
            'React',
            'Tailwind',
            'Next JS',
            'Node',
            'Express',
            'CI/CD',
            'MongoDB',
            'Postgresql',
            'ORM Prisma',
            'Docker',
            'AWS Cloud',
            'Redis',
            'Kafka',
            'RabitMQ',
            'BullMQ',
        ],
        recentProject: 'proflowers.com (Admin UI & APIs)',
        availability: 'Immediate Joiner',
    },
};